classDiagram
    class Пользователь {
        -number идентификатор
        -string электроннаяПочта
        -string пароль
        -string полноеИмя
        +Файл[] файлы
    }

    class Файл {
        -number идентификатор
        -string имяФайла
        -string оригинальноеИмя
        -number размер
        -string типMIME
        -number идентификаторПользователя
        -Date датаСоздания
        -Date датаУдаления
        -boolean вИзбранном
        +Пользователь пользователь
    }

    %% Связь между сущностями
    Пользователь "1" *-- "*" Файл : владеет
    Файл "*" --> "1" Пользователь : принадлежит
