import Head from "next/head";
import { GetServerSidePropsContext } from "next";

import { checkAuth } from "@/utils/checkAuth";

export default function Home() {
  return (
    <>
      <Head>
        <title>CloudStorage</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
    </>
  );
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const authProps = await checkAuth(ctx);

  if ("redirect" in authProps) {
    return authProps;
  }
};
